# Generated by Django 4.2.30 on 2026-05-27 09:50

import devoirs.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devoir',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('fichier', models.FileField(blank=True, null=True, upload_to=devoirs.models.devoir_upload_path)),
                ('deadline', models.DateTimeField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('notif_j2_envoyee', models.BooleanField(default=False)),
                ('notif_j1_envoyee', models.BooleanField(default=False)),
                ('notif_deadline_envoyee', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoirs', to='classes.classe')),
            ],
        ),
        migrations.CreateModel(
            name='Soumission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fichier', models.FileField(upload_to=devoirs.models.soumission_upload_path)),
                ('commentaire', models.TextField(blank=True)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('note', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('devoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soumissions', to='devoirs.devoir')),
                ('eleve', models.ForeignKey(limit_choices_to={'role': 'eleve'}, on_delete=django.db.models.deletion.CASCADE, related_name='soumissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('eleve', 'devoir')},
            },
        ),
    ]
